### ISSUE TITLE
Question about icra2024_gl

### ISSUE THREAD

**Issue by chengwei0427** [koide3/glil_pubdoc#1]
Hi, @koide3 

Happy New Year.

I have read your ICRA2024 paper (_Tightly Coupled Range Inertial Localization on a 3D Prior Map_),I have two questions I'd like to get your advice on.

1.  Move from an unmapped area to a mapped area, if the cumulative error is too large, whether an abnormal pose jump occurs? How to deal with it?
![image](https://github.com/koide3/glil_pubdoc/assets/20199999/8b1e31f0-a7cd-4ac9-9fa7-6c5867048914)

2. Whether to determine whether the point cloud is degenerated or not?  I mean, as you can see from the figure, the degenerated laser frames has only preintegrated IMU constraints.
![image](https://github.com/koide3/glil_pubdoc/assets/20199999/23fd8db7-c040-466d-92c6-523631037def)

**Comment by koide3** [comment]
1. In most cases, the proposed method smoothly corrects cumulative errors by simultaneously considering consecutive scan matching and scan-to-map matching. However, if the error is very large (after traveling unmapped regions for a long time), it would cause a map matching failure.

2. We do not explicitly determine if a point cloud is degenerate but simply insert every degenerate matching cost factor into the graph and jointly minimize them (i.e., tight coupling). Such degenerate factors still provided constraints with limited DoFs (e.g., 5 DoF constraint in the case in the figure) and help reducing estimation errors.

**Comment by chengwei0427** [comment]
Hi, @koide3 
Thanks for your patience.
For the first question, how canyou deal with that   _`if the error is very large (after traveling unmapped regions for a long time), it would cause a map matching failure.`_

**Comment by koide3** [comment]
In that case, we need to perform re-localization. While it is not in the scope of this paper, we have developed a global localization algorithm for this purpose in another paper https://arxiv.org/abs/2310.10023 .

**Comment by chengwei0427** [comment]
Thanks. Problem solved.
